name: gmnerf
channels:
  - nvidia/label/cuda-11.7.1
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - backcall=0.2.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.1.31
  - comm=0.2.2
  - cuda-cccl=11.7.91
  - cuda-command-line-tools=11.7.1
  - cuda-compiler=11.7.1
  - cuda-cudart=11.7.99
  - cuda-cudart-dev=11.7.99
  - cuda-cuobjdump=11.7.91
  - cuda-cupti=11.7.101
  - cuda-cuxxfilt=11.7.91
  - cuda-documentation=11.7.91
  - cuda-driver-dev=11.7.99
  - cuda-gdb=11.7.91
  - cuda-libraries=11.7.1
  - cuda-libraries-dev=11.7.1
  - cuda-memcheck=11.7.91
  - cuda-nsight=11.7.91
  - cuda-nsight-compute=11.7.1
  - cuda-nvcc=11.7.99
  - cuda-nvdisasm=11.7.91
  - cuda-nvml-dev=11.7.91
  - cuda-nvprof=11.7.101
  - cuda-nvprune=11.7.91
  - cuda-nvrtc=11.7.99
  - cuda-nvrtc-dev=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-nvvp=11.7.101
  - cuda-sanitizer-api=11.7.91
  - cuda-toolkit=11.7.1
  - cuda-tools=11.7.1
  - cuda-visual-tools=11.7.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - einops=0.8.0
  - executing=2.1.0
  - expat=2.6.4
  - freetype=2.10.4
  - gds-tools=1.3.1.18
  - h5py=3.11.0
  - hdf5=1.12.1
  - imageio=2.36.0
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.12.2
  - jbig=2.1
  - jedi=0.19.1
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=11.10.3.66
  - libcublas-dev=11.10.3.66
  - libcufft=10.7.2.91
  - libcufft-dev=10.7.2.91
  - libcufile=1.3.1.18
  - libcufile-dev=1.3.1.18
  - libcurand=10.2.10.91
  - libcurand-dev=10.2.10.91
  - libcurl=7.88.1
  - libcusolver=11.4.0.1
  - libcusolver-dev=11.4.0.1
  - libcusparse=11.7.4.91
  - libcusparse-dev=11.7.4.91
  - libdeflate=1.7
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - liblapack=3.9.0
  - libmpdec=4.0.0
  - libnghttp2=1.57.0
  - libnpp=11.7.4.75
  - libnpp-dev=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libnvjpeg-dev=11.8.0.2
  - libopenblas=0.3.29
  - libpng=1.6.37
  - libsodium=1.0.18
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuuid=1.41.5
  - libwebp-base=1.5.0
  - lz4-c=1.9.3
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nsight-compute=2022.2.1.3
  - olefile=0.47
  - openjpeg=2.4.0
  - openssl=3.4.1
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - python=3.8.18
  - python-dateutil=2.9.0
  - python_abi=3.8
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.0
  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - appdirs==1.4.4
      - async-timeout==5.0.1
      - attrs==25.1.0
      - blessed==1.22.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - contourpy==1.1.1
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - fonttools==4.57.0
      - frozenlist==1.5.0
      - fsspec==2025.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gpustat==1.1.1
      - idna==3.10
      - importlib-resources==6.4.5
      - jinja2==3.1.6
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lightning-utilities==0.11.9
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - multidict==6.1.0
      - nerfacc==0.3.5+pt112cu113
      - ninja==1.11.1.3
      - numpy==1.24.4
      - nvidia-ml-py==13.580.82
      - opt-einsum==3.4.0
      - pandas==2.0.3
      - pillow==10.4.0
      - propcache==0.2.0
      - protobuf==4.25.6
      - psutil==7.0.0
      - pyg-lib==0.4.0+pt112cu113
      - pygments==2.19.1
      - pyparsing==3.1.4
      - pytz==2025.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - rich==13.9.4
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - sentry-sdk==2.22.0
      - setproctitle==1.3.5
      - six==1.17.0
      - smmap==5.0.2
      - threadpoolctl==3.5.0
      - tinycudann==1.7
      - torch==1.12.0+cu113
      - torch-cluster==1.6.3
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2
      - torch-sparse==0.6.18
      - torch-spline-conv==1.2.2
      - torchmetrics==1.5.2
      - torchvision==0.13.0+cu113
      - tqdm==4.67.1
      - tzdata==2025.2
      - urllib3==2.2.3
      - wandb==0.16.0
      - yarl==1.15.2
